import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Layout from "@/app/components/common/Layout";
import Footer from "@/app/components/elements/footer/Footer";
import ResultsBlock from "@/app/components/elements/sections/resultsBlock/ResultsBlock";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <div className={styles.content}>
                    <ResultsBlock/>
                    <Footer/>
                </div>
            </Layout>
        </>
    );
}
